### ISSUE TITLE
Anzeigefehler

### ISSUE THREAD

**Issue by kkschneider** [KONDE-AT/maechtekongresse-static#10]
Information, von wessen Hand das Schriftstück ist, fehlt

Bei mehreren Anhängen: Abschnittsanzeige fehlt (z. B. Prot. Aachen 30)

Rechtsbündige Elemente werden linksbündig dargestellt (z. B. Datum) - z. T. fehlt der Zeilenumbruch (z. B. Prot. Aachen 30 Ende)

Bei Links werden Abkürzungsauflösungen gleichberechtigt neben Abkürzungen dargestellt (z. B. Mr. Monsieur Cte Comte de Palmella - Prot. Aachen 30)

Zitierempfehlungen werden nicht angezeigt.

**Comment by skurzinz** [comment]
- [x] Bei mehreren Anhängen: Abschnittsanzeige fehlt (z. B. Prot. Aachen 30)

- [x] Rechtsbündige Elemente werden linksbündig dargestellt (z. B. Datum) - z. T. fehlt der Zeilenumbruch (z. B. Prot. Aachen 30 Ende)

- [x] Bei Links werden Abkürzungsauflösungen gleichberechtigt neben Abkürzungen dargestellt (z. B. Mr. Monsieur Cte Comte de Palmella - Prot. Aachen 30)

- [x] Zitierempfehlungen werden nicht angezeigt.

- [x] Information, von wessen Hand das Schriftstück ist, fehlt

**Comment by skurzinz** [comment]
Links with nested entities should work now (54eab17)

**Comment by skurzinz** [comment]
done for this part of the list
