### ISSUE TITLE
Cookie-Info

### ISSUE THREAD

**Issue by kkschneider** [KONDE-AT/maechtekongresse-static#12]
ist noch nicht vorhanden

**Comment by skurzinz** [comment]
@csae8092 Does dse-cookiecutter store any cookies locally? Is there a need to do any GDPR conformance stuff?

**Comment by csae8092** [comment]
cookies are only used if you used matomo tracking which are not in the current version; and I'd recommend to keep it like this. One day in a bright future ACDH-CH will set up sophisticated server-log monitoring which will make matomo obosolete anyways...
