### ISSUE TITLE
Metadaten

### ISSUE THREAD

**Issue by kkschneider** [KONDE-AT/maechtekongresse-static#13]
Super, sind wieder da!

Mir ist aber aufgefallen, dass "Anwesende" bzw. "Regest" und vielleicht noch mehr unterpungiert sind und beim mouseover auf tei-Sachen verweisen.

**Comment by skurzinz** [comment]
Code ist übernommen und macht genau das, was die exist-app machen sollte. Die title-Attribute sagen, welches tei-Element da ausgegeben wird, von daher ist das nach wie vor ein grundsätzlich sinnvolles Feature, dessen Entfernung aufwändiger wäre als die Verwirrung allfälliger BenutzerInnen zu beruhigen?
