### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by kkschneider** [KONDE-AT/maechtekongresse-static#14]
Bevor ich noch eine Suche eingegeben hatte, wurden mir gleich 113 Treffer angezeigt.

**Comment by skurzinz** [comment]
Das ist wohl ein feature, insofern als die Suche filternd einschränkt, also erst einmal alles da ist. Das hilft für die initiale Filterung nach Dokumenten anhand der Facetten links, so kann auch nach allen Dok gesucht werden, die aus Troppau stammen und eine Person und einen Ort referenzieren, ohne dass ein Stichwort dabei ist. 

Das funktioniert wunderbar, Lob dafür an tabulator-js und an @csae8092, ich mach das hier wieder zu.
