### ISSUE TITLE
make modals work

### ISSUE THREAD

**Issue by csae8092** [KONDE-AT/maechtekongresse-static#5]
at least a little bit

**Comment by csae8092** [comment]
@skurzinz so, turns out you must not use `.` in your entity `@ref|@xml:id` as e.g.  `'#loc.1' is not a valid selector`
therefore I suggest to you run a one time script to change you ids, e.g. replace `.` with `-`

**Comment by skurzinz** [comment]
A little bit: works. 

Needs more attention to multiple references such as `ref="#p_1 #p_2"` etc. 
Will try to reuse the schnitzler-tagebuch-static code for this.

**Comment by skurzinz** [comment]
@kkschneider bitte prüfen

**Comment by skurzinz** [comment]
works as expected, no negative user feedback. may be reopened if such appears.
