### ISSUE TITLE
Metadaten zu einzelnen Dokumenten

### ISSUE THREAD

**Issue by kkschneider** [KONDE-AT/maechtekongresse-static#9]
Neben den Regesten und Anwesenden Personen (gestern schon besprochen) fehlen weitere Metadaten:
- Dokumentenart
- Ort/Datum
- Signatur
- Stückbeschreibung
- Verweise zu Drucken

Nicht nur für Protokolle, sondern auch für Anhänge zu Protokollen (z. B. Prot. Aachen 30)

**Comment by skurzinz** [comment]
277d82b9 uncollapse button
